services:
  # Backend API Service
  - type: web
    name: my-react-app-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables here:
    # - key: MONGODB_URI
    #   fromDatabase:
    #     name: your-mongodb-database
    #     property: connectionString
    # - key: JWT_SECRET
    #   generateValue: true

  # Frontend Static Site
  - type: static
    name: my-react-app-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://my-react-app-api.onrender.com

# Optional: Database (if using MongoDB)
# databases:
#   - name: my-react-app-db
#     databaseName: myreactapp
#     user: myuser